### ISSUE TITLE
application

### ISSUE THREAD

**Issue by magic-fortune** [FDU-VTS/MMAC#1]
Greetings! I noticed that the MICCAI 2023 Macular Degeneration Detection Challenge has already concluded, however, I am interested in conducting research in this area. May I kindly inquire about the possibility of obtaining the dataset used for this competition?

    Best regards！

**Comment by houjunlin** [comment]
Hi, this is MICCAI 2023 Myopic Maculopathy Analysis Challenge. You may visit https://codalab.lisn.upsaclay.fr/competitions/12441#participate to get data.
